name: Lint checks
on:
  pull_request:
    branches:
    - main
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@7.26.3 --activate

      - name: Test build
        run: make build

      - name: ESlint
        run: pnpm run lint
        
      - name: Storybook
        run: pnpm run build-storybook
