name: Publish
on: [workflow_dispatch]
jobs:
  # publishing azure artifacts
  azure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup original .npmrc file to download packages
      - uses: timheuer/base64-to-file@v1.1
        with:
          fileName: '.npmrc'
          fileDir: .
          encodedString: ${{ secrets.NPMRC }}
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn publish ./packages/flow-core