name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: create env file
        run: |
          pwd
          touch packages/flow-core/.env
          echo FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }} >> .env
          echo FILE_KEY=${{ secrets.FIGMA_FILE_KEY }} >> .env
          cat packages/flow-core/.env

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}